[project]
channels = ["conda-forge"]
name = "hhnk-threedi-tools"
platforms = ["win-64", "linux-64"]
version = "2025.1"
repository = "https://github.com/threedi/hhnk-threedi-tools"


[target.win-64.tasks]
hrt-install = "binpixi/install_hrt.cmd"

[target.linux-64.tasks]
hrt-install = "bash binpixi/install_hrt.sh"


[tasks]
#Starting vs code using vs-code.cmd (pixi run code)
lab = "jupyter lab"
code = "code"
code_insiders = "code-insiders"

pre-commit-install = "pre-commit install --install-hooks -t=pre-push" #-t=pre-commit
postinstall = { depends-on = ["hrt-install", "pre-commit-install"] }

pre-commit-run = "pre-commit run --all-files"

# Upload to PyPi to make it available with pip
upload_pypi = "twine upload --repository hhnk-threedi-tools  dist/*"

[feature.dev.tasks]
#Styling
sort_imports = "python -m ruff check  ./**/*.py --select I --fix --force-exclude"
fmt = "python -m ruff format ./**/*.py --force-exclude"
style = {depends-on = ["sort_imports", "fmt"]} # `pixi run style`

[feature.test.tasks]
tests = "pytest --cov-report term-missing --cov=hhnk_threedi_tools --cov-report=xml tests/"


[dependencies]
python = "3.12.*"
# MI 3.40 site packages
geopandas = "==1.0.1"
numpy = "==1.26.4"
openpyxl = "*"  # 3.1.2
pandas = "==2.2.2"
scipy = "==1.13.0"
urllib3 = "2.*" #2.2.3

# HHNK deps
# affine # rxr dep
cached_property = "*"
# branca # folium dep
# dask # rxr dep
dask = "*"
folium = "*"
gdal = "*"
# See also: https://discourse.matplotlib.org/t/latest-versions-via-pip-jupyterlab-import-of-matplotlib-broken/24477/7
matplotlib = "*"  # 3.9.0 gives RuntimeError: Entry point name 'inline' duplicated
# rasterio # rxr dep
rasterstats = "*"
rioxarray = "*"
rtree = "*"
seaborn = "*"
oracledb = "*"
pyogrio = "*"
pytest = "*"
pytest-cov = "*"
tqdm = "*"
xarray = "*"
# xyzservices # folium dep


pip = "*"

[pypi-dependencies]
# NenS deps
threedi-api-client = "==4.1.12"
threedi-modelchecker = "==2.18.3"
threedi-schema = "==0.300.26"
threedi-scenario-downloader = "*"
threedi_mi_utils = "==0.1.10"
threedigrid = "==2.3.5"
threedigrid-builder = ">=1.24.3"
threedidepth = "==0.6.3"

# HHNK deps
hhnk-threedi-tools = { path = ".", editable = true }

[feature.dev.dependencies]
jupyterlab = "*"
ipywidgets = "*"
jupytext = "*"
pre-commit = "*"
twine="*"
ruff = "*"

# DataCheker
flask = "*"  # oude datachecker
sqlparse = "*"  # oude datachecker
psycopg2 = "*"  # oude datachecker
fastapi = "*"  # nieuwe datachecker
uvicorn = "*"  # nieuwe datachecker
django = "<4"  # datachecker (<4 wegens compatibility met 3Di modules)


[feature.dev.pypi-dependencies]
# Editable installs, not installed on test. #FIXME doesnt work on Github Actions.
# https://github.com/prefix-dev/pixi/issues/2763
# FIXME disabled. should run pixi run postinstall
# hhnk-research-tools = { path = "../hhnk-research-tools", editable = true }


[feature.test.pypi-dependencies]
hhnk-research-tools = { git = "https://github.com/hhnk/hhnk-research-tools.git", rev = "main" }


[environments]
dev = ["dev"]
test = { features=["test"], no-default-feature = false }