[project]
channels = ["conda-forge"]
name = "hhnk-threedi-tools"
platforms = ["win-64"]
version = "2024.1"
repository = "https://https://github.com/threedi/hhnk-threedi-tools"

[tasks]
sort_imports = "python -m ruff check . --select I --fix"
fmt = "python -m ruff format ./**/*.py --force-exclude"
style = {depends-on = ["sort_imports", "fmt"]} # `pixi run style`
tests = "pytest --cov-report term-missing --cov=hhnk_threedi_tools --cov-report=xml tests/"

qgis = "qgis --profiles-path .pixi/qgis_env"

[dependencies]
python = "3.12.*" # equals MI python version
geopandas = ">1"
pandas = "2.*"
scipy = "*"
h5py = "*" # Incompatible met rest van env; conda solved naar 3.11.0
fiona = "*"
shapely = "*"

#User folder
jupyterlab = "*"
ipywidgets = "*"
jupytext = "*"

pytest = "*"
pytest-cov = "*"
pluggy = "*" # pytest dependency
iniconfig = "*" # pytest dependency
tqdm = "*"
rioxarray = "*" # higher versions need python >=3.10
pyogrio = "*" # 0.9.0 doesnt work with gdal
rasterio = "*" # rxr dep
affine = "*" # rxr dep
dask = "*" # rxr dep
matplotlib = "*" # 3.9.0 gives RuntimeError: Entry point name 'inline' duplicated
# See also: https://discourse.matplotlib.org/t/latest-versions-via-pip-jupyterlab-import-of-matplotlib-broken/24477/7
seaborn = "*"

xarray = "*"
openpyxl = "*"
cached_property = "*"
rtree = "*"
oracledb = "*"
pip = "*"
urllib3 = "<2.0"
# qgis = "3.40.*"
# qgis-plugin-manager = "*"
ruff = "*"

[pypi-dependencies]
threedi_modelchecker = "*" # threedi_results_analysis 3.9.0
threedi_scenario_downloader = "*" # Lizard API v4 only
threedi_schema = "==0.219.3" # threedi_results_analysis 3.9.0
threedi-api-client = "*" # 3Di Models and Simulations 3.11.0
threedigrid_builder = "<1.24" # threedi_results_analysis 3.9.2 FIXME 1.24 cant be imported.
threedigrid = "*" # threedi_results_analysis 3.12.0
threedidepth = "*" # threedi_results_analysis 3.9.0

#Editable isntalls
hhnk_threedi_tools = { path = ".", editable = true }
hhnk_research_tools = { path = "../hhnk-research-tools", editable = true }


[feature.py312.dependencies]
python = "3.12.*"


[environments]
default = ["py312"]