# columns
lvl_start_col = 'lvl_start'
lvl_end_col = 'lvl_end'
lvl_rain_col = 'lvl_rain'
lvl_end_rain_col = 'lvl_end_rain'

# Hydraulic tests
res_orifices = 'orifices'
res_channels = 'channels'
res_culverts = 'culverts'

start_node_col = 'start_node'
end_node_col = 'end_node'
code_col = 'code'
flow_direction_col = 'flow_direction'
slope_col = 'slope'
water_lvl_diff_col = 'wtr_lvl_diff_m'
q_col = 'q'
u_var_col = 'u'
slope_abs_cm_km_col = 'slope_abs_cm_km'
waterlevel_diff_abs_m_col = 'wlvl_diff_abs_m'
map_id_col = 'map_id'
zoom_cat_col = 'zoom_cat'
upstream_id_col = 'upstream_id'
downstream_id_col = 'downstream_id'
waterlevel_up_end_col = 'wlvl_end_up'
waterlevel_down_end_col = 'wlvl_end_down'
waterlevel_up_start_col = 'wlvl_start_up'
waterlevel_down_start_col = 'wlvl_start_down'
struct_on_lvl_limit_col = 'on_lvl_area_limit'
id_col = 'id'
index_col = 'index'
primary_col = 'is_primary'
waterlevel_t_0_col = 'wtrlvl_t0'
waterlevel_t_end_col = 'wtrlvl_t_end'
