DEFAULT_NESS = [
    {
        "name": "waterlevel_1d",
        "geom_type": "Point",
        "element": "nodes",
        "attribute_name": "wlvl",
        "attribute": "s1",
        "subset": "1D_All",
        "methods": ["min", "max"],
        "aggregation_name": "s1_max",
    },
    {
        "name": "volume_1d",
        "geom_type": "Point",
        "element": "nodes",
        "attribute_name": "vol",
        "attribute": "vol",
        "subset": "1D_All",
        "methods": ["min", "max"],
        "aggregation_name": "vol_max",
    },
    {
        "name": "waterlevel_2d",
        "geom_type": "Polygon",
        "element": "nodes",
        "attribute_name": "wlvl",
        "attribute": "s1",
        "subset": "2D_OPEN_WATER",
        "methods": ["min", "max"],
        "aggregation_name": "s1_max",
    },
    {
        "name": "volume_2d",
        "geom_type": "Polygon",
        "element": "nodes",
        "attribute_name": "vol",
        "attribute": "vol",
        "subset": "2D_OPEN_WATER",
        "methods": ["min", "max"],
        "aggregation_name": "vol_max",
    },
    {
        "name": "infiltration",
        "geom_type": "Polygon",
        "element": "nodes",
        "attribute_name": "infilt",
        "attribute": "infiltration_rate_simple",
        "subset": "2D_OPEN_WATER",
        "methods": ["sum"],
        "aggregation_name": "infiltration_rate_simple_avg",
    },
    {
        "name": "interception",
        "geom_type": "Polygon",
        "element": "nodes",
        "attribute_name": "incept",
        "attribute": "intercepted_volume",
        "subset": "2D_OPEN_WATER",
        "methods": ["sum"],
        "aggregation_name": "intercepted_volume_current",
    },
    {
        "name": "rain",
        "geom_type": "Polygon",
        "element": "nodes",
        "attribute_name": "rain",
        "attribute": "rain",
        "subset": "2D_OPEN_WATER",
        "methods": ["sum"],
        "aggregation_name": "rain_avg",
    },
    {
        "name": "discharge_1d",
        "geom_type": "LineString",
        "element": "lines",
        "attribute_name": "q",
        "attribute": "q",
        "subset": "1D_All",
        "methods": ["max", "min", "sum", "sum_pos", "sum_neg"],
        "aggregation_name": "q_avg",
    },
    {
        "name": "velocity_1d",
        "geom_type": "LineString",
        "element": "lines",
        "attribute_name": "u1",
        "attribute": "u1",
        "subset": "1D_All",
        "methods": ["max", "min", "max_abs"],
        "aggregation_name": "u1_max",
    },
]
