name: Pytests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


# Automatically stop old builds on the same branch/PR
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  default:
    if: |
      github.event_name == 'push' ||
      github.event.pull_request.draft == false
    strategy:
      matrix:
        os: ["windows-latest", ]
        python-version: [ "py39", ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.8
        with:
          pixi-version: "latest"
          cache: true
          # cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          environments: ${{ matrix.python-version }}
      
      
      - name: Run ruff
        shell: bash
        run: |
          pixi run -e py39 ruff check --select I --force-exclude && \
          pixi run -e py39 ruff format --check --force-exclude

      - name: Run Tests
        run: pixi run -e py39 tests tests/
        env: 
          SKIP_DATABASE: "1"

      - name: Upload coverage
        uses: codecov/codecov-action@v5