name: tests

on:   
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"
      - "unitest-codecov"

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true


jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        # Slow; solve env during action
        # python-version: 3.9
        # miniconda-version: "latest"
        # channels: conda-forge,defaults
        # channel-priority: true
        activate-environment: hhnk_threedi
        # environment-file: envs\environment_test.yml

        #semi slow; solve env once. using conda-lock -f envs/environment.yml -p win-64 --kind=explicit          ##drag result to envs dir.
        auto-update-conda: false
        # activate-environment: explicit-env
        # environment-file: envs/conda-win-64.lock
        environment-file: envs/environment.yml
    - name: Test
      shell: pwsh
      run: |
        conda info
        conda list
        pip install -e .
        python -m pytest --cov-report term-missing --cov=hhnk_threedi_tools tests/
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
    